
pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    service_name: project-assessment-site-service
    service_type: REST
spec:
  containers:
  - name: dnd
    image: docker:latest
    command: 
    - cat
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  - name: kubectl
    image: bryandollery/terraform-packer-aws-alpine
    command:
    - cat
    tty: true
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock  
      type: Socket
"""
    }
  }
  environment {
    CREDS = credentials('rayanah_docker_tocker')
    DOCKER_NAMESPACE = 'rayanah'
    SERVICE_NAME = 'project-assessment-site-service'
    TOKEN=credentials('68248c47-ebfb-4d27-a9d3-5d759c957eb3')
  }
  stages {
      stage("Build") {
          steps {
              container('dnd') {
                  sh '''
                      cd project-assessment-site
                      docker build --tag $DOCKER_NAMESPACE/$SERVICE_NAME .
                  '''
              }
          }
      }
      stage("Release") {
          steps {
              container('dnd') {
                  sh '''
                      docker login -p $CREDS_PSW -u $CREDS_USR
                      docker push $DOCKER_NAMESPACE/$SERVICE_NAME
                  '''
              }
          }
      }
      stage("Deploy") {
          steps {
              container('kubectl') {
                  sh '''
                      cd project-assessment-site
                      kubectl --token=$TOKEN -n jenkins apply -f deploy.yaml -f service.yaml
                  '''
              }
          }
      }
  }
}
